---
title: "R for Business Code Snippets"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)

bikes_tbl           <- read_excel("00_data/bike_sales/data_raw/bikes.xlsx")
orderlines_tbl      <- read_excel("00_data/bike_sales/data_raw/orderlines.xlsx")
bike_orderlines_tbl <- read_rds("00_data/bike_sales/data_wrangled/bike_orderlines.rds")
```


```{r separate}
bike_orderlines_wrangled_tbl <- bike_orderlines_joined %>% 
     separate(description, into = c("category.1", "category.2", "frame.material"),
                                    sep = " - ", remove = TRUE) %>% 
     
     separate(location, into = c("city", "state"),
                                    sep = ", ", remove = FALSE) %>% 
     
     mutate(total.price = price * quantity) %>% 
     
     select(-location) %>% 
     select(-ends_with(".id")) %>% 
     
     bind_cols(bike_orderlines_joined %>% select(order.id)) %>% 
     
     select(contains("date"), contains("id"), contains("order"), quantity, price, total.price, everything()) %>% 
     
     rename(order_date = order.date) %>% 
     set_names(names(.) %>% str_replace_all("\\.", "_"))  

```

```{r fs}
fs::dir_create("00_data/bike_sales/data_wrangled_student")
```

```{r}
bike_orderlines_tbl %>% filter(!(category_2 %in% c("Over Mountain", "Trail", "Endurance Road")))

bikes_tbl %>% arrange(desc(price)) %>% slice((n()-4):n())


bike_orderlines_prices %>% mutate(is_supersix = model %>% str_to_lower() %>% str_detect("supersix")) %>% 
     filter(is_supersix) 
```

```{r str_func}
bikeshop_revenue_tbl %>% set_names(names(.) %>% str_replace("_", " ") %>% str_to_title())

bikeshop_revenue_formatted_tbl %>% gather(key = "catergory_1", value = "Sales", Mountain, Road) %>% ################################
        mutate(Sales = Sales %>% str_remove_all("\\$|,") %>% as.double()) %>% 
        arrange(desc(Sales))

```

```{r lag}
bike_sales_y_tbl %>%
    mutate(sales_lag_1 = lag(sales, n = 1)) %>%
    
    # Handle NA
    mutate(sales_lag_1 = case_when(
        is.na(sales_lag_1) ~ sales,
        TRUE ~ sales_lag_1
    )) %>%
    
    # Diff's & Pct Diffs
    mutate(diff_1 = sales - sales_lag_1) %>%
    mutate(pct_diff_1 = diff_1 / sales_lag_1) %>%
    mutate(pct_diff_1_chr = scales::percent(pct_diff_1))
```

```{r dplyr_first}
bike_sales_y_tbl %>%
    mutate(sales_2011 = first(sales)) %>%
    mutate(diff_2011  = sales - sales_2011) %>%
    mutate(pct_diff_2011 = diff_2011 / sales_2011) %>%
    mutate(pct_diff_2011_chr = scales::percent(pct_diff_2011))
```

```{r dplyr_cum}
bike_sales_m_tbl %>%
    
    group_by(year) %>%
    
    mutate(cumulative_sales = cumsum(sales)) %>%
    mutate(cumulative_sales_pct = cumulative_sales / sum(sales)) %>%
    mutate(cumulative_sales_pct_chr = scales::percent(cumulative_sales_pct))
```

```{r zoo_rollmean}
bike_sales_m_tbl %>%
    
    mutate(roll_mean_3 = rollmean(sales, k = 3, na.pad = TRUE, align = "right", fill = NA)) %>%
    
    mutate(roll_mean_6 = rollmean(sales, k = 6, na.pad = TRUE, align = "right", fill = NA))
```

```{r between}
bike_orderlines_tbl %>%
    
    mutate(order_date = ymd(order_date)) %>%
    
    filter(order_date %>% between(left = ymd("2012-01-01"), right = ymd("2013-12-31"))) # dates are inclusive
```

```{r dplyr_funcs2}
# Replacing text in column names

bike_orderlines_tbl %>%
     set_names(names(.) %>% str_replace("_", ".") %>% str_to_upper())

# Appending text to column names

bike_orderlines_tbl %>%
     set_names(str_glue("{names(.)}_bike"))

# Appending text to specific column names
bike_orderlines_colnames_tbl <- bike_orderlines_tbl %>%
     rename_at(.vars = vars(model:frame_material), 
               .funs = ~ str_c("prod_", .)) %>%
     rename_at(vars(bikeshop_name:state),
               ~ str_c("cust_", .)) 
```

